spring:
  datasource:
    url: jdbc:h2:mem:batchdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jpa:
   properties:
     generate-ddl: true
     hibernate:
       dialect: org.hibernate.dialect.H2Dialect
       show_sql: false
       ddl-auto: create
  batch.job.enabled: false